FROM node:18.10-alpine AS build
WORKDIR /dist/src/app

RUN npm cache clean --force

COPY . .
RUN npm install
RUN npm run build --omit=dev

FROM nginx:latest AS ngi

COPY --from=build /dist/src/app/dist/typlio-client /usr/share/nginx/html
COPY /nginx.conf  /etc/nginx/conf.d/default.conf

EXPOSE 80
